### ISSUE TITLE
Getting data as string from number picker

### ISSUE THREAD

**Issue by mangeshghotage** [code-troopers/android-betterpickers#183] opened 2015-07-15 06:30 UTC
I need to get raw string which has entered using NumberPicker. Later i want to convert it into a BigDecimal. The event is giving number in double which can be inaccurate for currencies. So, it should also give raw string.

**Comment by fchauveau** [comment] 2016-01-14 10:42
duplicate of #213 
Returning entered value as String will not be implemented

**Closed as completed by fchauveau** 2016-01-14 10:42 UTC
